#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-desktop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=32 \
    color=0x66494d64 \
    margin=0 \
    sticky=on \
    padding_left=0 \
    padding_right=0 \
    notch_width=188 \

sketchybar --default \
    background.height=32 \
    icon.color=0xff24273a \
    icon.font="$FONT_FACE:Medium:20.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=0xff24273a \
    label.font="$FONT_FACE:Bold:14.0" \
    label.y_offset=1 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:23.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no #\
    # --add item front_app.name left \
    # --set front_app.name \
    # background.color=0x00000000 \
    # icon.drawing=off \
    # label.font="$FONT_FACE:Bold:16.0" \
    # label.color=0xffcad3f5 \
    # label.padding_left=5

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    background.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add event aerospace_workspace_change

# for sid in $(aerospace list-workspaces --all); do
#     sketchybar --add item space.$sid left \
#         --subscribe space.$sid aerospace_workspace_change \
#         --set space.$sid \
#         background.color=0x44ffffff \
#         background.corner_radius=5 \
#         background.height=20 \
#         background.drawing=off \
#         label="$sid" \
#         click_script="aerospace workspace $sid" \
#         script="$PLUGIN_SHARED_DIR/plugins/aerospace.sh $sid"
# done

# Add workspaces for all monitors
for monitor in $(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id}"); do
  for sid in $(aerospace list-workspaces --monitor "$monitor"); do
    # Determine which display this workspace should be shown on
    display_id="1"
    if [ "$sid" -ge 7 ] && [ "$sid" -le 9 ]; then
      display_id="2"
    fi
    
    sketchybar --add item space.$sid left \
      --set space.$sid display="$display_id" \
      --subscribe space.$sid aerospace_workspace_change \
      --set space.$sid \
      drawing=on \
      background.color=0x44ffffff \
      background.corner_radius=5 \
      background.drawing=on \
      background.border_color=0xAAFFFFFF \
      background.border_width=0 \
      background.height=25 \
      icon="$sid" \
      icon.padding_left=10 \
      icon.shadow.distance=4 \
      icon.shadow.color=0xA0000000 \
      label.font="sketchybar-app-font:Regular:16.0" \
      label.padding_right=20 \
      label.padding_left=0 \
      label.y_offset=-1 \
      label.shadow.drawing=off \
      label.shadow.color=0xA0000000 \
      label.shadow.distance=4 \
      click_script="aerospace workspace $sid" \
      script="$PLUGIN_SHARED_DIR/aerospace.sh $sid"
  done
done

# Load Icons on startup for all monitors
for monitor in $(aerospace list-monitors); do
  for sid in $(aerospace list-workspaces --monitor "$monitor" --empty no); do
    apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

    sketchybar --set space.$sid drawing=on

    icon_strip=" "
    if [ "${apps}" != "" ]; then
      while read -r app; do
        icon_strip+=" $($PLUGIN_SHARED_DIR/icon_map_fn.sh "$app")"
      done <<<"${apps}"
    else
      icon_strip=""
    fi
    sketchybar --set space.$sid label="$icon_strip"
  done
done

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
