#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"

DISPLAY_COUNT=$(aerospace list-monitors --count 2>/dev/null)
if (( ${DISPLAY_COUNT:-1} == 1 )); then
    export SKETCHYBAR_LAPTOP=1
else
    unset SKETCHYBAR_LAPTOP
fi

source "$SKETCHYBAR_CONFIG/sketchybarrc-desktop"
